
def init_config(dataid):

# 公共配置
    common_config = {
        'gpu': '0',
        'interval': 25,
        'mr': 0,
        'temperature_ins' : 1.0,
        'temperature_clu' : 0.5,
        'save_model' : False,
        'k_neighbors' : 5,
        'test_times' : 1,
        'seed': 2025
    }
# 独立配置
    config_dict = {
        0: {
            **common_config,
            'dataid': 0,
            'dataname': 'MSRC-v2',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1,
            'beta' : 1e-4,
            'gamma' : 1e-3,
            'train_epochs' : 200,
            'k_neighbors' : 3,
            'hidden_feas':[2500,2500]
            },
        1: {
            **common_config,
            'dataid': 1, 
            'dataname': 'Scene15',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 100,
            },
        2: {
            **common_config, 
            'dataid': 2, 
            'dataname': 'NoisyMNIST30000',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 100,
            },
        3: {
            **common_config, 
            'dataid': 3, 
            'dataname': 'CCV',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 100,
            },
        4: {
            **common_config, 
            'dataid': 4, 
            'dataname': 'NUSWIDEOBJ',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 100,
            },
        5: {
            **common_config, 
            'dataid': 5, 
            'dataname': 'Caltech256_fea',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 100,
            },
        6: {
            **common_config, 
            'dataid': 6, 
            'dataname': '100leaves',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 200,
            },
        7: {
            **common_config, 
            'dataid': 7, 
            'dataname': 'COIL20',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 400,
            'hidden_feas': [1500,1500]
            },
        8: {
            **common_config, 
            'dataid': 8, 
            'dataname': '3sources',
            'toArray': True,
            'out_fea': 512,
            'bs' : 64,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 400,
            },
        9: {
            **common_config, 
            'dataid': 9, 
            'dataname': 'NGs',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 400,
            },
        10: {
            **common_config, 
            'dataid': 10, 
            'dataname': 'handwritten',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1,
            'beta' : 1e-4,
            'gamma' : 1e-5,
            'train_epochs' : 200,
            'hidden_feas': [1500,1500]
            },
        11: {
            **common_config, 
            'dataid': 11, 
            'dataname': 'BBCSport',
            'toArray': True,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 400,
            },
        12: {
            **common_config, 
            'dataid': 12, 
            'dataname': 'Caltech101-7',
            'toArray': False,
            'out_fea': 512,
            'bs' : 500,
            'train_lr' : 1e-4,
            'alpha' : 1e-4,
            'beta' : 1e-5,
            'gamma' : 1e-3,
            'train_epochs' : 400,
            'hidden_feas':  [500,2000]
            },
        13: {
            **common_config, 
            'dataid': 13, 
            'dataname': 'YaleB',
            'toArray': False,
            'out_fea': 512,
            'bs' : 256,
            'train_lr' : 1e-4,
            'alpha' : 1e-3,
            'beta' : 1e-2,
            'gamma' : 1e-1,
            'train_epochs' : 400,
            'hidden_feas':  [1000,1000,1000]
            }
        # 可以继续添加其他 dataid 的配置
    }
    return config_dict.get(dataid)